blank_issues_enabled: false
contact_links:
  - name: Questions
    url: https://discord.gg/8ZmhaPPbjE
    about: "Please ask questions on the Luna Pixel Studios Discord (in #fuzs-projects) or contact me directly on Discord at Fuzs#0212."