blank_issues_enabled: false
contact_links:
  - name: Questions
    url: https://discord.gg/8ZmhaPPbjE
    about: Please ask questions on the Luna Pixel Studios Discord or contact me directly at Fuzs#0212.