name: Crash Report
description: >-
  Please use this template when this mod has caused your game to crash.
title: '[Crash]: '
labels: ["bug"]
assignees:
  - Fuzss
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this issue report!
  - type: dropdown
    id: loader
    attributes:
      label: Mod Loader (Required)
      description: What mod loader are you using the mod on?
      multiple: false
      options:
        - Forge
        - Fabric
        - Quilt
    validations:
      required: true
  - type: input
    id: minecraft
    attributes:
      label: Minecraft Version (Required)
      description: What is the Minecraft version you are playing with?
      placeholder: ex. 1.19
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Mod Version (Required)
      description: What version of the mod are you playing with?
      placeholder: ex. v4.0.0
    validations:
      required: true
  - type: textarea
    id: notes
    attributes:
      label: Notes (Required)
      description: Please explain which steps we need to do to reproduce the crash. Please include anything else you'd like to say about the crash.
      placeholder: >-
        ex.  
        
        1. Open the furnace screen.

        2. Shift-click a fuel item into the fuel slot.

        3. The game crashes.
    validations:
      required: true
  - type: input
    id: crash-report
    attributes:
      label: Crash Report (Required)
      description: >-
        Please paste the url to your shared crash report. [To share your crash report here, please follow these steps.](https://gist.github.com/Fuzss/9692f6ed5e8cca485a58004c28c9045b)
      placeholder: ex. https://gist.github.com/<your_user_name>/<gist_id>
    validations:
      required: true
  - type: input
    id: latest-log
    attributes:
      label: latest.log (Optional)
      description: Please paste the url to your shared `latest.log` file. [To share your `latest.log` here, please follow these steps.](https://gist.github.com/Fuzss/866b384d353912986e37b17eeef7a285)
      placeholder: ex. https://gist.github.com/<your_user_name>/<gist_id>