name: Crash Report
description: >-
  Please use this template when this mod has caused your game to crash.
title: '[Crash]: '
labels: ["bug"]
assignees:
  - Fuzss
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this issue report!
  - type: dropdown
    id: loader
    attributes:
      label: Mod Loader (Required)
      description: What mod loader are you using the mod on?
      multiple: false
      options:
        - Forge
        - Fabric
        - Quilt
    validations:
      required: true
  - type: input
    id: minecraft
    attributes:
      label: Minecraft Version (Required)
      description: What is the Minecraft version you are playing with?
      placeholder: ex. 1.19
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Mod Version (Required)
      description: What version of the mod are you playing with?
      placeholder: ex. v4.0.0
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: Steps to Reproduce the Crash (Required)
      description: Please explain what we need to do to cause the crash.
      placeholder: >-
        Example:  
        
        1. Open the furnace screen.

        2. Shift-click a fuel item into the fuel slot.

        3. The game crashes.
    validations:
      required: true
  - type: textarea
    id: notes
    attributes:
      label: Additional Notes (Optional)
      description: >-
        Optionally, please include anything else you'd like to say about the crash.
      placeholder: >-
        Example:

        I warned everyone on my server not to do this, so nobody is crashing any more. 
        I just thought I should let you know so you can fix it, thanks!
    validations:
      required: false
  - type: markdown
    attributes:
      value: >-
        ## Sharing your Crash Report
        
        In order to diagnose a crash, we will need to see your crash report.

        To share your crash report here, please follow these steps:


        1. If you don't have it already, find your crash report file.

        a. [Find your minecraft
        folder](https://minecraft.fandom.com/wiki/.minecraft)

        b. In the minecraft folder, go into the `crash-reports` folder and find
        the most recent crash report file.

        1. Create a Gist from the crash report file and copy the url.

        [Click here for instructions on creating a
        Gist](https://gist.github.com/Fuzss/bb307f86159b0011fcc2e10364a1b0a7)
  - type: input
    id: crashlog
    attributes:
      label: Crash Report (Required)
      description: >-
        Please paste the url to the gist containing your crash report.
      placeholder: https://gist.github.com/<your_user_name>/<gist_id>
    validations:
      required: true
  - type: markdown
    attributes:
      value: >-
        ## Sharing your `latest.log`

        In order to diagnose a bug, we will need to see your `latest.log`.

        To share your `latest.log` here, please follow these steps:


        1. If you don't have it already, find your `latest.log` file.

        a. [Find your minecraft
        folder](https://minecraft.fandom.com/wiki/.minecraft)

        b. In the minecraft folder, go into the `logs` folder and find the
        `latest.log` file.

        1. Create a Gist from the `latest.log` and copy the url.

        [Click here for instructions on creating a
        Gist](https://gist.github.com/Fuzss/bb307f86159b0011fcc2e10364a1b0a7)
  - type: input
    id: latest-log
    attributes:
      label: latest.log (Optional)
      description: Please paste the url to the gist containing your `latest.log` file.
      placeholder: https://gist.github.com/<your_user_name>/<gist_id>